### PR TITLE
webpack@5 update

### PR DESCRIPTION
**Pull request by JoeCMorgan**
Pull request to update this plugin to be compatible with webpack version 5, as the current plugin is not supported. This is obviously a breaking change. I'll add some more in the next few days so it handles both version 4.x and version 5 of webpack.

### CODE REVIEW

**Comment by mzohaibqc** [comment]
Thanks a lot @JoeCMorgan for your valueable contribution. 👍

**Comment by JoeCMorgan** [comment]
@mzohaibqc it's ready for review now when you get a chance. I've tested it on both webpack 5 & 4, and it all looks good. However I would suggest some testing of the defaultOptions, as I've just tested the standard implementation:
```
      new AntDesignThemePlugin({
        publicPath : isProduction ? '/' : ''
      }),
```

**Comment by mzohaibqc** [comment]
@JoeCMorgan Thanks a lot and I really appreciate this. I'll review and test this PR soon (within 2-3 days) and everything will work well, I'll publish new changes to npm package.

**Comment by MarkLyck** [comment]
@mzohaibqc any update to this review?

**Comment by mzohaibqc** [comment]
@JoeCMorgan I pulled this code and tried to use this in existing example project inside this repo `examples/customize-cra` but it did not work due to added webpack@v5 dependency. So in order to use this, one must be using webpack 5 otherwise it will not work.

If you can fix this issue, I'll merge this otherwise I've to wait and find more time to come up with solution.

@MarkLyck  FYI ^

**Comment by JoeCMorgan** [comment]
Good spot @mzohaibqc, apologies for not testing that. I've now removed the webpack 5 dependency, and added it as a peer dependency, which should work for both webpack version 4 and 5. I've tested it in with `examples/customize-cra` and it works fine, and I've also tested it with my own webpack 5 project and it's working.

Let me know if you find any more issues with the PR and I'll happily fix them.

**Comment by mzohaibqc** [comment]
@JoeCMorgan  Thank you so much for this effort. I'll look into this on weekend and will merge and publish new version.

**Review by mzohaibqc — APPROVED** [review]
LGTM

**Comment by mzohaibqc** [comment]
@JoeCMorgan  Thanks for this PR. I've merged this PR and published new version to npm.

antd-theme-webpack-plugin@1.3.8

**Pull request merged**
