### PR TITLE
Forked

### PR DESCRIPTION
**Pull request by JoeCMorgan**
Remove arrow methods from class

### CODE REVIEW

**Comment by JoeCMorgan** [comment]
@mzohaibqc PR to remove the arrow functions. I've tested with webpack@5 and it works fine, so I don't see why it wouldn't work with webpack@4. There are still arrow functions inside the methods, however the've been in there since before version 1.3.8, so I think it was just an issue having arrow functions as class methods. 

I'm not sure why github thinks there are so many file changes in this PR, as most of them are already in master 🤔

**Comment by mzohaibqc** [comment]
@JoeCMorgan  your branch is not updated with master. Kindly pull master branch from main repository into your branch and it will fix too many changes.

**Comment by JoeCMorgan** [comment]
Apologies, as you said I had forgotten to pull your master branch into my fork. Should be sorted now

**Review by mzohaibqc — APPROVED** [review]

**Comment by mzohaibqc** [comment]
@JoeCMorgan Thanks, I've merged and published a new version i.e. 1.3.9

**Comment by JoeCMorgan** [comment]
@mzohaibqc No problem at all, apologies about that. I'll keep and eye on the raised issue.

**Pull request merged**
